//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop

#include "u_SeedData.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

const TSeedContinentRow SeedContinents[] =
{
	{ scEurope,       L"Europe" },
	{ scAsia,         L"Asia" },
	{ scAfrica,       L"Africa" },
	{ scNorthAmerica, L"North America" },
	{ scSouthAmerica, L"South America" },
	{ scOceania,      L"Australia and Oceania" }
};
const int SeedContinentCount = sizeof(SeedContinents) / sizeof(SeedContinents[0]);
//---------------------------------------------------------------------------
// Страны из экспорта uCoin.net (названия — как в столбце Country).
// Исчезнувшие государства: реальный континент + IsExist = false.
const TSeedCountryRow SeedCountries[] =
{
	{ L"Afghanistan",                    scAsia,          true  },
	{ L"Albania",                        scEurope,        true  },
	{ L"Algeria",                        scAfrica,        true  },
	{ L"Argentina",                      scSouthAmerica,  true  },
	{ L"Armenia",                        scAsia,          true  },
	{ L"Aruba",                          scNorthAmerica,  true  },
	{ L"Australia",                      scOceania,       true  },
	{ L"Austria",                        scEurope,        true  },
	{ L"Azerbaijan",                     scAsia,          true  },
	{ L"Bahamas",                        scNorthAmerica,  true  },
	{ L"Bahrain",                        scAsia,          true  },
	{ L"Bangladesh",                     scAsia,          true  },
	{ L"Barbados",                       scNorthAmerica,  true  },
	{ L"Belarus",                        scEurope,        true  },
	{ L"Belgium",                        scEurope,        true  },
	{ L"Belize",                         scNorthAmerica,  true  },
	{ L"Bermuda",                        scNorthAmerica,  true  },
	{ L"Bolivia",                        scSouthAmerica,  true  },
	{ L"Bosnia and Herzegovina",         scEurope,        true  },
	{ L"Botswana",                       scAfrica,        true  },
	{ L"Brazil",                         scSouthAmerica,  true  },
	{ L"British East Africa",            scAfrica,        false },
	{ L"Bulgaria",                       scEurope,        true  },
	{ L"Burundi",                        scAfrica,        true  },
	{ L"Cambodia",                       scAsia,          true  },
	{ L"Canada",                         scNorthAmerica,  true  },
	{ L"Cape Verde",                     scAfrica,        true  },
	{ L"Cayman Islands",                 scNorthAmerica,  true  },
	{ L"Ceylon",                         scAsia,          false },
	{ L"Chile",                          scSouthAmerica,  true  },
	{ L"China",                          scAsia,          true  },
	{ L"Colombia",                       scSouthAmerica,  true  },
	{ L"Congo - DRC",                    scAfrica,        true  },
	{ L"Cook Islands",                   scOceania,       true  },
	{ L"Costa Rica",                     scNorthAmerica,  true  },
	{ L"Croatia",                        scEurope,        true  },
	{ L"Cuba",                           scNorthAmerica,  true  },
	{ L"Cyprus",                         scEurope,        true  },
	{ L"Czech Republic",                 scEurope,        true  },
	{ L"Czechoslovakia",                 scEurope,        false },
	{ L"Denmark",                        scEurope,        true  },
	{ L"Dominican Republic",             scNorthAmerica,  true  },
	{ L"Dutch Republic",                 scEurope,        false },
	{ L"East Timor",                     scAsia,          true  },
	{ L"Eastern Caribbean",              scNorthAmerica,  true  },
	{ L"Ecuador",                        scSouthAmerica,  true  },
	{ L"Egypt",                          scAfrica,        true  },
	{ L"El Salvador",                    scNorthAmerica,  true  },
	{ L"Eritrea",                        scAfrica,        true  },
	{ L"Estonia",                        scEurope,        true  },
	{ L"Eswatini (Swaziland)",           scAfrica,        true  },
	{ L"Ethiopia",                       scAfrica,        true  },
	{ L"Falkland Islands",               scSouthAmerica,  true  },
	{ L"Fiji",                           scOceania,       true  },
	{ L"Finland",                        scEurope,        true  },
	{ L"France",                         scEurope,        true  },
	{ L"French Polynesia",               scOceania,       true  },
	{ L"Gambia",                         scAfrica,        true  },
	{ L"Georgia",                        scAsia,          true  },
	{ L"Germany",                        scEurope,        true  },
	{ L"Germany - GDR",                  scEurope,        false },
	{ L"Germany - Third Reich",          scEurope,        false },
	{ L"Ghana",                          scAfrica,        true  },
	{ L"Gibraltar",                      scEurope,        true  },
	{ L"Greece",                         scEurope,        true  },
	{ L"Guatemala",                      scNorthAmerica,  true  },
	{ L"Guernsey",                       scEurope,        true  },
	{ L"Guinea",                         scAfrica,        true  },
	{ L"Guyana",                         scSouthAmerica,  true  },
	{ L"Haiti",                          scNorthAmerica,  true  },
	{ L"Hong Kong",                      scAsia,          true  },
	{ L"Hungary",                        scEurope,        true  },
	{ L"Iceland",                        scEurope,        true  },
	{ L"India",                          scAsia,          true  },
	{ L"India - British",                scAsia,          false },
	{ L"Indonesia",                      scAsia,          true  },
	{ L"Iran",                           scAsia,          true  },
	{ L"Iraq",                           scAsia,          true  },
	{ L"Ireland",                        scEurope,        true  },
	{ L"Isle of Man",                    scEurope,        true  },
	{ L"Israel",                         scAsia,          true  },
	{ L"Italy",                          scEurope,        true  },
	{ L"Jamaica",                        scNorthAmerica,  true  },
	{ L"Japan",                          scAsia,          true  },
	{ L"Jersey",                         scEurope,        true  },
	{ L"Jordan",                         scAsia,          true  },
	{ L"Kazakhstan",                     scAsia,          true  },
	{ L"Kenya",                          scAfrica,        true  },
	{ L"Kuwait",                         scAsia,          true  },
	{ L"Kyrgyzstan",                     scAsia,          true  },
	{ L"Laos",                           scAsia,          true  },
	{ L"Latvia",                         scEurope,        true  },
	{ L"Lebanon",                        scAsia,          true  },
	{ L"Libya",                          scAfrica,        true  },
	{ L"Lithuania",                      scEurope,        true  },
	{ L"Lombardy-Venetia",               scEurope,        false },
	{ L"Luxembourg",                     scEurope,        true  },
	{ L"Macau",                          scAsia,          true  },
	{ L"Madagascar",                     scAfrica,        true  },
	{ L"Malawi",                         scAfrica,        true  },
	{ L"Malaya and British Borneo",      scAsia,          false },
	{ L"Malaysia",                       scAsia,          true  },
	{ L"Malta",                          scEurope,        true  },
	{ L"Mauritius",                      scAfrica,        true  },
	{ L"Mexico",                         scNorthAmerica,  true  },
	{ L"Moldavia and Wallachia",         scEurope,        false },
	{ L"Moldova",                        scEurope,        true  },
	{ L"Monaco",                         scEurope,        true  },
	{ L"Mongolia",                       scAsia,          true  },
	{ L"Morocco",                        scAfrica,        true  },
	{ L"Mozambique",                     scAfrica,        true  },
	{ L"Myanmar",                        scAsia,          true  },
	{ L"Namibia",                        scAfrica,        true  },
	{ L"Nepal",                          scAsia,          true  },
	{ L"Netherlands",                    scEurope,        true  },
	{ L"Netherlands Antilles",           scNorthAmerica,  false },
	{ L"New Caledonia",                  scOceania,       true  },
	{ L"New Zealand",                    scOceania,       true  },
	{ L"Nicaragua",                      scNorthAmerica,  true  },
	{ L"Nigeria",                        scAfrica,        true  },
	{ L"North Korea",                    scAsia,          true  },
	{ L"North Macedonia",                scEurope,        true  },
	{ L"Norway",                         scEurope,        true  },
	{ L"Oman",                           scAsia,          true  },
	{ L"Ottoman Empire",                 scAsia,          false },
	{ L"Pakistan",                       scAsia,          true  },
	{ L"Panama",                         scNorthAmerica,  true  },
	{ L"Papua New Guinea",               scOceania,       true  },
	{ L"Paraguay",                       scSouthAmerica,  true  },
	{ L"Peru",                           scSouthAmerica,  true  },
	{ L"Philippines",                    scAsia,          true  },
	{ L"Poland",                         scEurope,        true  },
	{ L"Portugal",                       scEurope,        true  },
	{ L"Prussia",                        scEurope,        false },
	{ L"Qatar",                          scAsia,          true  },
	{ L"Rhodesia",                       scAfrica,        false },
	{ L"Romania",                        scEurope,        true  },
	{ L"Russia",                         scEurope,        true  },
	{ L"Russian Empire",                 scEurope,        false },
	{ L"Rwanda",                         scAfrica,        true  },
	{ L"San Marino",                     scEurope,        true  },
	{ L"Saudi Arabia",                   scAsia,          true  },
	{ L"Serbia",                         scEurope,        true  },
	{ L"Seychelles",                     scAfrica,        true  },
	{ L"Singapore",                      scAsia,          true  },
	{ L"Slovakia",                       scEurope,        true  },
	{ L"Slovenia",                       scEurope,        true  },
	{ L"Solomon Islands",                scOceania,       true  },
	{ L"Somalia",                        scAfrica,        true  },
	{ L"South Africa",                   scAfrica,        true  },
	{ L"South Korea",                    scAsia,          true  },
	{ L"Spain",                          scEurope,        true  },
	{ L"Sri Lanka",                      scAsia,          true  },
	{ L"Sudan",                          scAfrica,        true  },
	{ L"Suriname",                       scSouthAmerica,  true  },
	{ L"Sweden",                         scEurope,        true  },
	{ L"Switzerland",                    scEurope,        true  },
	{ L"Syria",                          scAsia,          true  },
	{ L"S\u00E3o Tom\u00E9 and Pr\u00EDncipe", scAfrica,        true  },
	{ L"Taiwan",                         scAsia,          true  },
	{ L"Tanzania",                       scAfrica,        true  },
	{ L"Thailand",                       scAsia,          true  },
	{ L"Tokelau",                        scOceania,       true  },
	{ L"Tonga",                          scOceania,       true  },
	{ L"Transnistria",                   scEurope,        true  },
	{ L"Trinidad and Tobago",            scNorthAmerica,  true  },
	{ L"Tunisia",                        scAfrica,        true  },
	{ L"Turkey",                         scAsia,          true  },
	{ L"Turkmenistan",                   scAsia,          true  },
	{ L"USA",                            scNorthAmerica,  true  },
	{ L"USSR",                           scEurope,        false },
	{ L"Uganda",                         scAfrica,        true  },
	{ L"Ukraine",                        scEurope,        true  },
	{ L"United Arab Emirates",           scAsia,          true  },
	{ L"United Kingdom",                 scEurope,        true  },
	{ L"Uruguay",                        scSouthAmerica,  true  },
	{ L"Uzbekistan",                     scAsia,          true  },
	{ L"Vanuatu",                        scOceania,       true  },
	{ L"Vatican City",                   scEurope,        true  },
	{ L"Venezuela",                      scSouthAmerica,  true  },
	{ L"Vietnam",                        scAsia,          true  },
	{ L"Western Africa (BCEAO)",         scAfrica,        true  },
	{ L"Yemen",                          scAsia,          true  },
	{ L"Yugoslavia",                     scEurope,        false },
	{ L"Zaire",                          scAfrica,        false },
	{ L"Zambia",                         scAfrica,        true  },
	{ L"Zimbabwe",                       scAfrica,        true  }
};
const int SeedCountryCount = sizeof(SeedCountries) / sizeof(SeedCountries[0]);
//---------------------------------------------------------------------------
